import { auth } from "@/auth"
import { redirect } from "next/navigation"
import fs from "fs"
import path from "path"

export default async function ReportsPage() {
  const session = await auth();
  
  if (!session?.user) {
    // Redirect unauthenticated users to login
    redirect("/api/auth/signin");
  }

  const reportsDir = path.join(process.cwd(), '..', 'reports');
  
  let reports: any[] = [];
  try {
    if (fs.existsSync(reportsDir)) {
      const files = fs.readdirSync(reportsDir);
      reports = files.filter(f => f.endsWith('.pdf') || f.endsWith('.md')).map(file => {
          const nameWithoutExt = path.parse(file).name;
          // Expecting format like "Gold_PortfolioManager"
          const parts = nameWithoutExt.split('_');
          const metal = parts[0];
          const agent = parts.slice(1).join(' '); // In case agent name has underscores
          
          return {
              filename: file,
              metal: metal || 'Unknown Metal',
              agent: agent || 'Unknown Agent',
              downloadUrl: `/api/reports/download?file=${file}`
          };
      });
    }
  } catch (e) {
    console.error("Error reading reports directory", e);
  }

  return (
    <div className="min-h-screen bg-black text-white p-8 font-sans">
      <div className="max-w-6xl mx-auto">
        <header className="mb-12 border-b border-yellow-500/20 pb-6 flex justify-between items-center">
          <div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-yellow-200 via-yellow-500 to-yellow-700 text-transparent bg-clip-text">
              Metal Detectors
            </h1>
            <p className="text-gray-400 mt-2">Intelligence Reports Dashboard</p>
          </div>
          <div className="flex items-center gap-4">
             <span className="text-sm text-gray-400">{session.user.email}</span>
             <form action="/api/auth/signout" method="POST">
                <button type="submit" className="text-sm px-4 py-2 bg-yellow-500/10 text-yellow-500 rounded hover:bg-yellow-500/20 transition-colors">
                  Sign Out
                </button>
             </form>
          </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reports.length === 0 ? (
            <div className="col-span-full text-center py-12 border border-yellow-500/10 rounded-xl bg-gray-900/50">
               <p className="text-gray-400 text-lg">No reports found.</p>
               <p className="text-sm text-gray-500 mt-2">
                 Generate reports locally and save them to the <code className="text-yellow-500/70">MetalDetectors/reports</code> folder.
               </p>
               <p className="text-xs text-gray-600 mt-1">Naming format: Metal_AgentName.pdf (e.g., Gold_PortfolioManager.pdf)</p>
            </div>
          ) : (
            reports.map((report) => (
              <div key={report.filename} className="border border-yellow-500/20 bg-gray-900/40 rounded-xl p-6 hover:border-yellow-500/50 transition-all group relative overflow-hidden">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-yellow-500 to-yellow-700 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <h3 className="text-2xl font-semibold text-yellow-500 mb-1">{report.metal}</h3>
                <p className="text-gray-400 text-sm mb-6">Generated by: <span className="text-gray-300 font-medium">{report.agent}</span></p>
                
                <div className="flex gap-3">
                  <a href={report.downloadUrl} download={report.filename} className="flex-1 bg-gradient-to-b from-yellow-400 to-yellow-600 text-black text-center py-2 rounded font-semibold hover:from-yellow-300 hover:to-yellow-500 transition-all shadow-[0_0_15px_rgba(234,179,8,0.15)] group-hover:shadow-[0_0_20px_rgba(234,179,8,0.3)]">
                    Download
                  </a>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}
